### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#1]
Use Case №1: Login
Primary Actor: User
Pre Condition: Installed browser and active internet connection 
Main scenario:
1.	User initiates browser
2.	User specifies web address for accessing the CRM
3.	User gives the login and password
4.	System does authentication
5.	Activity Stream is displayed
Alternate scenario:
 	4.1 Authorization fails – wrong username/password
  		4.1.1 Prompt the user that he typed the username/password wrong
 		4.1.2 Allow him to re-enter the username/password
 	4.2 Authorization fails – forgotten username/password
 		4.2.1 Prompt the user to enter his registered email
 		4.2.2 User receives an email with instructions about his login credentials

**Comment by qaprovers** [comment]
Login works **as expected**. Bugs were **not found**.
The following automated test cases were done:
1.	Valid email AND Valid password - pass - **"Active Stream"** is displayed
2.	Valid email AND Wrong password - pass - **"Incorrect login or password"** is displayed
3.	Wrong email AND Wrong password - pass - **"Incorrect login or password"** is displayed
4.	Wrong email AND Valid password - pass - **"Incorrect login or password"** is displayed
5.	Only valid email - pass - **"Incorrect login or password"** is displayed
6.	Only NOT valid type of an email - **"Incorrect login or password"** is displayed
7.	Only wrong email - pass - **"Incorrect login or password"** is displayed
8.	Only valid password - pass - **"Incorrect login or password"** is displayed
9.	Only wrong password - pass - **"Incorrect login or password"** is displayed
10.	Forgotten password with valid email - pass - received **email with instructions**
11.	Email with instructions - pass - **received and working**
12.	Forgotten password with wrong email - pass - **Login or E-mail not found** is displayed

**Comment by qaprovers** [comment]
Automation Test of Use Case №1
https://gist.github.com/devprovers/fe0df8989b3fba425da6

**Comment by devprovers** [comment]
Great!
