### ISSUE TITLE
New Event

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#10]
Use Case №10: New Event
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User initiates the “New Event” functionality from Calendar (left pane, refer user screens in Appendix )
2.	User enters start and end time and sets reminders
3.	User specifies event name and location
4.	User specifies event description
5.	User adds participants (if needed) 
6.	User submits the event
7.	Event is created
8.	System sends notifications to the participants
9.	System sends reminders
Alternate scenario:
 	6.1 New Event cancellation
  		6.1.1. User cancels New Event functionality
 		6.1.2. New Task canceled

**Comment by qaprovers** [comment]
New Event works **as expected**. Bugs were **not found**.
Manual test case scenarios were done.
