### ISSUE TITLE
Delete Event

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#11]
Use Case №11: Delete Event
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User selects the event from Calendar (left pane, refer user screens in Appendix )
2.	User initiates the “Delete Event” functionality from the event itself
3.	System displays a confirmation message
4.	Event is deleted

**Comment by qaprovers** [comment]
Delete Event works **as expected**. Bugs were **not found**.
Manual test case scenarios were done.
