### ISSUE TITLE
Add Contact

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#12]
Use Case №12: Add Contact
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User initiates the “Add Contact” functionality from CRM/Contacts (left pane, refer user screens in Appendix )
2.	User specifies first and last names of the contact
3.	User specifies email
4.	User specifies phone
5.	User specifies Company (if necessary) 
6.	User specifies contact type
7.	User specifies responsible person
8.	A contact is created
Alternate scenario:
 	8.1. Add Contact cancelation
  		8.1.1. “Add Contact” functionality is canceled
 	8.2. Contact with the same information exists
 		8.2.1. System asks the user for different information
 			8.2.1. Contact is created
 		8.2.2. System asks the user for merging with existing contact
 			8.2.1. Contact is merged
 		8.2.3. System cancels the “Add Contact” functionality

**Comment by qaprovers** [comment]
Add Contact works **as expected**. Bugs were **not found**.
An IDE test case scenarios was done.
