### ISSUE TITLE
Delete Contact

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#13]
Use Case №13: Delete Contact
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User selects the contact from CRM/Contacts (left pane, refer user screens in Appendix )
2.	User initiates the “Delete Contact” functionality from the contact itself
3.	System displays a confirmation message
4.	Contact is deleted

**Comment by qaprovers** [comment]
Delete Contact works **as expected**. Bugs were **not found**.
Manual test case scenarios was done.
