### ISSUE TITLE
Add Company

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#14]
Use Case №14: Add Company
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User initiates the “Add Company” functionality from CRM/Companies (left pane, refer user screens in Appendix )
2.	User specifies company name
3.	User specifies responsible person
4.	User specifies company information
5.	User associates employees / contacts  (if present) 
6.	User submits the company form
Alternate scenario:
 	6.1. Add Company cancelation
  		6.1.1. “Add Company” functionality is canceled
 	6.2. Company with the same information exists
 		6.2.1. System asks the user for different information
 			6.2.1. Company is created
 		6.2.2. System asks the user for merging with existing Company
 			6.2.1. Company is merged
 		6.2.3. System cancels the “Add Company” functionality

**Comment by qaprovers** [comment]
Add Company works **as expected**. Bugs were **not found**.
An IDE test case scenarios was done.
