### ISSUE TITLE
Delete Company

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#15]
Use Case №15: Delete Company
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User selects the company from CRM/Companies (left pane, refer user screens in Appendix )
2.	User initiates the “Delete Company” functionality from the company itself
3.	System displays a confirmation message
4.	Company is deleted

**Comment by qaprovers** [comment]
Delete Company works **as expected**. Bugs were **not found**.
Manual test case scenarios was done.
