### ISSUE TITLE
Create Activity

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#16]
Use Case №16: Create Activity
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User initiates the “Create Activity” functionality from CRM/Activities (left pane, refer user screens in Appendix )
2.	User selects the activity type (new call or new meeting)
3.	User specifies date and reminder
4.	User specifies where/with information
5.	User specifies subject and information
6.	User specifies responsible person
7.	An activity is created
8.	System sends notification and reminders
Alternate scenario:
 	7.1 Create Activity cancellation
  		7.1.1. User cancels Create Activity functionality
 		7.1.2. Create Activity canceled

**Comment by qaprovers** [comment]
Create Activity works **as expected**. Bugs were **not found**.
Manual test case scenarios was done.
