### ISSUE TITLE
Finish Activity

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#17]
Use Case №17: Finish Activity
Primary Actor: User
Pre Condition: User logged in 
Scenario:
1.	User selects the activity from CRM/Activities (left pane, refer user screens in Appendix )
2.	User initiates the “Finish Activity” functionality from the activity itself
3.	System marks the activity as finished

**Comment by qaprovers** [comment]
Finish Activity works **as expected**. Bugs were **not found**.
Manual test case scenarios was done.
