### ISSUE TITLE
Delete Activity

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#18]
Use Case №18: Delete Activity
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User selects the activity from CRM/Activities (left pane, refer user screens in Appendix )
2.	User initiates the “Delete Activity” functionality from the activity itself
3.	System displays a confirmation message
4.	Activity is deleted

**Comment by qaprovers** [comment]
Delete Activity works **as expected**. Bugs were **not found**.
Manual test case scenarios was done.
