### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#2]
Use Case №2: Change password
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User goes to Bitrix24.Network Page from the profile menu located at the top
2.	User goes to Edit Profile
3.	User initiates “Change Password” functionality 
4.	User provides current password, new password and confirm new password
5.	System displays message for successful change 
Alternate scenario:
 	4.1 Authorization fails – current wrong password
  		4.1.1 Prompt the user that he typed the current password wrong
 		4.1.2 Allow him to re-enter the password
 	4.2 Authorization fails – new password and confirm new password do not match
 		4.2.1 Prompt the user that new password and confirm new password do not match
 		4.2.2 Allow him to re-enter the attributes.
 	4.3 Authorization fails – new password and confirm password are less than 6 chars
 		4.3.1 Prompt the user that password must be at least 6 characters
 		4.3.2 Allow him to re-enter new and confirm password

**Comment by qaprovers** [comment]
Login works **as expected**. Bugs were **not found**.
The following automated test case scenarios with Selenium IDE were done:
1. Valid password change - pass - **"Password has been changed successfully."** is displayed
2. Worng current AND new/confirm valid - pass - **"Current password is not correct"** is displayed
3. Worng current AND new/confirm not matching - pass - **"Current password is not correct"** is displayed
4. Worng current AND new/confirm less than 6 char - pass - **"Current password is not correct"** is displayed
5. Worng current AND new/confirm less than 6 char AND not matching - pass - **"The password must contain at least 6 symbols.Incorrect password confirmation"** is displayed
6. Valid current AND new/confirm password do not match - pass - **"Incorrect password confirmation"** is displayed
7. New and confirm password less than 6 char - pass - pass - **"The password must contain at least 6 symbols."** is displayed
