### ISSUE TITLE
Post Message

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#3]
Use Case №3: Post Message 
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User initiates “Post Message” functionality from Activity Stream 
2.	User enters message text
3.	User specifies attachments (if necessary)
4.	User specifies recipients
5.	User posts the message
6.	Message is created
7.	All recipients receive notification
Alternate scenario:
 	5.1 Post Message Cancellation
  		5.1.1. User cancels Post Message functionality
 		5.1.2. Post Message canceled

**Comment by qaprovers** [comment]
Post Message works **as expected**. Bugs were **not found**.
The following manual test case scenarios were done:
1.	Logging the user
2.	Initiating "Post Message" functionality from Active Stream
3.	Message is submitted and displayed in the Active Stream
4.	All recipients received notification
5.	“The message text is empty.” displayed when submitting an empty message to Active Stream
6.	“Please specify at least one person.” displayed when no recipient is specified
7.	Message attachments are accessible and visible from Active Stream
8.	“Post Message” cancelation works as expected. No message is posted.
