### ISSUE TITLE
Processes

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#5]
Use Case №5: Processes 
Primary Actor: User
Secondary Actor: User - Approver
Pre Condition: Users logged in 
Main scenario:
1.	User initiates “Processes” functionality from Activity Stream
2.	User selects type of needed approval
3.	User specifies absence type 
4.	User specifies reasons
5.	User sends the request approval
6.	Request is created
7.	Approver receives a notification about the request
8.	User receives approvers decision  
Alternate scenario:
 	5.1 Request Approval cancellation
  		5.1.1. User cancels Request Approval functionality
 		5.1.2. Request Approval canceled

**Comment by qaprovers** [comment]
Processes works **as expected**. Bugs were **not found**.
The following IDE test case scenarios were done:
1.	Logging the user
2.	From Activity Stream “Processes” is initiated
3.	Selecting the type of approval needed
4.	Specifying absence type
5.	Specifying reasons
6.	Sending the request
7.	Approver receives a notification
8.	User receives approvers decision 
9.	Alternative scenario works as well. Request is canceled.
