### ISSUE TITLE
New Task

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#6]
Use Case №6: New Task
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User initiates the “New Task” functionality from Tasks (left pane, refer user screens in Appendix )
2.	User enters a name for the task
3.	User specifies responsible person
4.	User specifies deadline for completion
5.	User enters the task description
6.	Task is created
7.	System creates and assigns the task to the responsible person
8.	System sends notification to the responsible person 
Alternate scenario:
 	6.1 New Task cancellation
  		6.1.1. User cancels New Task functionality
 		6.1.2. New Task canceled

**Comment by qaprovers** [comment]
New Task works **as expected**. Bugs were **not found**.
The following IDE test case scenarios were done:
1.	Logging the user
2.	Navigating to Tasks section
3.	Checking if Task section is loaded
4.	Creating a new task
5.	Checking if task is created
6.	Viewing the task
7.	Executing the task
8.	Checking if status is In Progress
9.	Finish the task
10.	Checking if status of the task is marked as Completed
