### ISSUE TITLE
Execute Task

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#7]
Use Case №7: Execute Task
Primary Actor: User
Pre Condition: User logged in 
Scenario:
1.	User selects task from Tasks (left pane, refer user screens in Appendix )
2.	User initiates the “Execute Task” functionality from the task itself
3.	Task execution is started

**Comment by qaprovers** [comment]
New Task works **as expected**. Bugs were **not found**.
The following IDE test case scenarios were done:
1.	Logging the user
2.	Navigating to Tasks section
3.	Checking if Task section is loaded
4.	Creating a new task
5.	Checking if task is created
6.	Viewing the task
7.	Executing the task
8.	Checking if status is In Progress
9.	Finish the task
10.	Checking if status of the task is marked as Completed
