### ISSUE TITLE
Delete Task

### ISSUE THREAD

**Issue by devprovers** [devprovers/QA-Teamwork-Provers#9]
Use Case №9: Delete Task
Primary Actor: User
Pre Condition: User logged in 
Main scenario:
1.	User selects task from Tasks (left pane, refer user screens in Appendix )
2.	User initiates the “Delete Task” functionality from the task itself
3.	System displays a confirmation message
4.	Task is deleted

**Comment by qaprovers** [comment]
Delete Task works **as expected**. Bugs were **not found**.
The following Manual test case scenarios were done:
1.	Selecting a task
2.	Starting the delete task functionality
3.	Display message for confirmation is displayed
4.	Task is deleted
